[Interface]
PrivateKey = WOjQSbVaBl1FTQFcH5I8h+YiiS+Hbop9Jc5o1+l6TUk=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,1.0.0.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = gNolCF9uNk7qoiGFJq9wd6rsm4AGy08H0YNd8jBn/WI=
PresharedKey = 4FNxQUzUG0YCY9HE84h3ytEiOC1atPqCngcDWd4vKXc=
Endpoint = 2.27.122.246:64114
AllowedIPs = 0.0.0.0/0,::/0